### ISSUE TITLE
Make the Gradle build file work with IDEA

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#13]
it would be really nice if our build script would talk to IntelliJ IDEA (which appears to have become our primary development platform). I had thought that the issue that causes it to fail (`Error: java.lang.String is not an interface`) was due to a  bug with the Scala plugin, but based on the fact that our [build file](https://github.com/hawkw/decaf/blob/master/build.gradle) for Decaf appears to work correctly with IDEA despite using the Scala plugin, I am not sure what the cause of this issue is, and I feel like it deserves more investigation.

This is not an actual Pathway issue, and doesn't really interfere that badly with development, but it would be really nice if it worked, so I'm making this issue. It's pretty low-priority, but if you have free time, I'd love to see this work.

**Comment by ArcticLight** [comment]
This is a bug of Major Inconvenience; If we are already planning on munging separate Java and Scala APIs do we still need genJavaDoc?

**Comment by hawkw** [comment]
If we can guarantee that the Scala and Java APIs will be 100% separate then yeah, we can drop genJavaDoc and be rid of this obnoxious problem.

**Comment by hawkw** [comment]
Oh hey, this was fixed around 10639080d5ae3fa2cc0037dc59e2c3b3f5eb01b4
