### ISSUE TITLE
Add 'freeze' or 'flatten' operation to ForkTable

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#21]
As described by @ArcticLight:
> Also, I was thinking of a primary optimization for Scope Table and I think I came up with an algorithm the API should call `freeze`. It's very simple, we recursively attempt to clone everything from the parent to the child nodes, then unlink parent from child. Because we only store child - > parent relationships (if I remember) it wouldn't affect children nodes that didn't participate in the freeze, but it would clone the data and make it much faster if we're not expecting to maintain all the various levels of lookups all the time.
Hence `freeze`, meaning "to freeze the table in this state"
Freezing is a long operation you do once to go from a mutable list of successive scopes to a frozen (each level mutable, but no longer chained) state. It takes you from O(_n_) worst case lookup time to guaranteed O(1), which if you're not expecting to mutate the tables anymore, would be a very important thing.

Why would one want such a thing? Read on:
>GameFileSystem, after constructing layers 1,2,and 3. It would improve lookup performance and we can trash any tables in between the references to those layers. We don't expect gameFS to change much, and even if it did, layer 1 by definition doesn't change its contents, and it would be trivial to manually manage layers 2-3 synchronicity

**Comment by hawkw** [comment]
I'm happy to take responsibility for this one. I'll probably start working on it once I've made some progress on the Great Test Mangling. I want to write a spec for `ForkTable` anyway, and I'll just go ahead and put tests for the relevant behavior in there while I'm at it so we can do TDD.

**Comment by ArcticLight** [comment]
:+1:

If you want me to do this, my environment is properly set up again and I am capable of Code Writing

**Comment by hawkw** [comment]
If you wanna do it, that's just fine. My goal was to hold off on it until I finish the spec describing `ForkTable` behavior for TDD fascism reasons, but w/e.

**Comment by hawkw** [comment]
Tests for `freeze` added in `test-refactor` 6e0e4a2a6d7e5641fa4c96630ddd13f74cff4376.

**Comment by hawkw** [comment]
This should be start-able approximately whenever. Probably @ArcticLight will want to merge `master` and `test-refactor` for his starting dev branch.

**Comment by hawkw** [comment]
Now that the tests for `freeze()` are in master, @ArcticLight can start on this whenever he's free.

**Comment by ArcticLight** [comment]
Yay! Waiting on my Internet to return from the land of the dead.

**Comment by hawkw** [comment]
AFAIK this is done.
