### ISSUE TITLE
Separate Java API from internal Scala API

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#22]
Since most of our internal code is written in Scala, it would be best if we could work completely in the Scala idiom and only convert to Java at the edges of our public-facing Java API. I'd like to also expose public elements of the Scala API as well so that other developers can write Pathway games completely in Scala. Regardless, we definitely want all internal code to be completely within the Scala idiom rather than having to munge things back and forth.

We may want to consider distributing the Pathway Java API as a separate library to Pathway Core, so that Scala-only developers can easily leave it out.

**Comment by ArcticLight** [comment]
This seems acceptable?

**Comment by hawkw** [comment]
See 802a04b0f9549841df9dc78db0f49ce09a901fca

**Comment by hawkw** [comment]
Okay, should I merge the `api-dev` branch, or shall we continue working on this project in the branch?

**Comment by hawkw** [comment]
N.B. that if we are following the practices of [semantic versioning](http://semver.org), this should push v2.0.

**Comment by hawkw** [comment]
Can we see about moving on this? There's a bunch of really gross Java compatibility crufts in `model._` that I'd love to nuke. They're keeping me from refactoring a lot of old code to the extent I'd really like to.

**Comment by hawkw** [comment]
Started on this one for real.

**Comment by hawkw** [comment]
d732a2eeaa16f0aa90bc6297048a6d5a7f6d9645 adds an initial working first pass on the new IO Scala API. It passes all tests on my dev box. There's potential for some additional clean-up, and some API ScalaDoc needs to be rewritten, but the API should be stable enough to start writing the Java compatibility layer.

**Comment by ArcticLight** [comment]
@ArcticLight did say this thing, and should begin working on it any time during his Copious Free Time.

**Comment by hawkw** [comment]
Great! I know you're pretty busy these days, so just start on this whenever `copiousFreeTime > 0`.

**Comment by hawkw** [comment]
Added the new Java `FileHandle` API in 55472bf0b9156f1d51634c08aca66fd18eed3f3e. I need to write documentation and tests, but then this should be done.

**Comment by hawkw** [comment]
Java `FileHandle` is finished as of d35ea5589e03bc08dad2724ee19c269c602320ab.
