### ISSUE TITLE
Pathway Spring Cleaning

### ISSUE THREAD

**Issue by ArcticLight** [MeteorCode/Pathway#25]
There appears to be a large number of old and possibly unused branches that exist in Pathway. I would like to get back into the codebase and start designing functionality, except that I have no idea where to start due to two pressing issues:

1. I have no idea what incarnation/branch of Pathway has the most recent code. Where are we working? What are the feature branches for? Is Master up-to-date such that I could fork off of it?
2. Our bug tracker is currently a mess, cluttered with Old and New and things that should probably be Iceboxed. We probably need to do some spring cleaning here as well.

**Comment by hawkw** [comment]
Master is currently completely up to date with everything that isn't in active dev.

The following feature branches are currently ahead of `master`:

+ `api-dev`: forked off of `master` 4 days ago, currently just contains a prototype of the Scala internal FileHandle API
+ `test-refactor`: contains all of the work I've been doing on the Great Test Embetterment project.
+ `wish`: I added an initial skeleton for a `Wish` to this branch several months ago. Besides that, it is several commits behind master.

The `gh-pages` branch is just used by Travis for publishing the API docs to GitHub Pages, so we don't need to mess with that. The `io-refac` branch contains changes to IO that have been merged into `master` for a while, it can (and probably should) be deleted.

**Comment by hawkw** [comment]
What's the status on this issue? Is this closable?

**Comment by hawkw** [comment]
Okay, I went ahead and deleted the `io-refac` and `test-refactor` branches. I'm not sure if we care about any of the code in the `api-dev` and `wish` dev branches.

**Comment by hawkw** [comment]
It looks like we can close this now that the test-refactoring stuff is merged in and we've pruned a number of the stale dev branches.
