### ISSUE TITLE
Coverage analysis for ScalaTest specs

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#28]
Currently, Gradle only knows how to collect coverage information for our old JUnit tests. Before the new ScalaTest specs can be used in production, I'd like to be able to collect coverage data for the new specs. This may necessitate switching from JaCoCo to another coverage analysis tool; if this is indeed the case, it might be worth looking into which coverage tools handle Scala code accurately, as I believe we've discussed in the past.

**Comment by hawkw** [comment]
Well, I checked out Scoverage, but it looks like Scoverage has no idea that Java classes even exist, which is a bummer. Meanwhile, JaCoCo doesn't seem to want to talk with ScalaTest. This requires further investigation.

**Comment by hawkw** [comment]
Okay, I've done some additional research, and it looks like this is due to maiflai/gradle-scalatest#18 - the Gradle ScalaTest plugin does not support JaCoCo.

The authors of the plugin likely will not add support for JaCoCo, based on the observation that "the Jacoco reports didn't help much when reviewing Scala code" (which is true). We therefore have a few alternative options here.

The authors of the Gradle ScalaTest plugin suggest using a different tool, such as Scoverage, which provides much more accurate coverage of Scala code, but (as I mentioned earlier) has no idea that Java even exists. I like Scoverage, and its reports are much more accurate and useful for Scala, but it means we'd be completely throwing coverage analysis for all our Java code under the bus. If the eventual goal is to move all of the main Pathway codebase to Scala and use Java only for compatibility/API layer, this might be acceptable. 

Alternatively, we could drop the ScalaTest plugin and use the ScalaTest [JUnit runner](http://www.scalatest.org/user_guide/using_junit_runner), which would have JUnit run all of our ScalaTest specs. This means we'd get the (frankly, somewhat less good) JUnit style test output rather than ScalaTest's, and we'd have to remember to add the `@RunWith` annotation to all of our specs, but we could have JaCoCo collect coverage information. We might also have some compatibility issues, as we're adding another layer of indirection here.

Finally, I think some people have managed to get JaCoCo, Scoverage, and ScalaTest to all play nice together in the same project (with JaCoCo collecting coverage data from Java code and Scoverage collecting coverage from Scala) by using [SonarQube](http://www.sonarqube.org/). This might be a lot of work to set up and configure an additional tool, but it could be the best choice in the long run.

I'm eager to know what @ArcticLight thinks about these various options.

**Comment by ArcticLight** [comment]
I think that, if we plan on implementing full-tilt-Scala as previously discussed, we may just switch to Scoverage and not test the Java end. The Java end should pretty much exist only as API shims anyway - Do we implement X interface? Good. I'm not saying I'm against testing and metrics, but when 90% of the expected Java code is "aninterface and anwrapper", it might be reasonable.

**Comment by hawkw** [comment]
> I think that, if we plan on implementing full-tilt-Scala as previously discussed, we may just switch to Scoverage and not test the Java end.

That is precisely what I had hoped you'd say. It might eventually be nice to run tests against the Java API wrappers as well, and if we do later want to do that, we can collect coverage information from them with a different coverage tool and use Sonar to generate reports, but we don't need to do that right away.

**Comment by ArcticLight** [comment]
If the wrappers are implemented in _scala_, we could probably test them just the same as everything else. The Java end would just be interface declarations.

**Comment by hawkw** [comment]
> If the wrappers are implemented in _scala_

Derp. I had not thought of that.
