### ISSUE TITLE
Determine and codify best practices and coding style

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#32]
~~Quick question: I know we obviously never want to break the CI build on `master`, but is it okay to push code that I know will break the build to a dev branch? I currently have some tests that are failing (see #31), and I want to write the fix on the IO dev branch. Is it okay to push the failing tests to the `test-refactor` branch before I write the fix?~~

Also, we should see about writing up a quick development best practices and coding style document to codify some of these things. I have Codacy's automated code review service set up to run code style analysis, but I haven't put the Codacy badge on the README because we haven't really worked out what coding style rules we want to follow. I vote tentatively for [Effective Scala](http://twitter.github.io/effectivescala/).

**Comment by hawkw** [comment]
Never mind, the first part of this issue is a moot point, the `io-refact` dev branch is way stale. I'll just make the fix on `master` and push the tests later. 

I'm leaving this open since we ought to have a discussion regarding dev policy.

**Comment by hawkw** [comment]
This is assigned to @ArcticLight because I'd like his input on it, not because he has to take sole responsibility for it.

**Comment by ArcticLight** [comment]
The Effective Scala document seems like a reasonable thing. Standards seem like a reasonable thing. Basically, I approve this message and approve of standards. I will need to read up on Effective Scala, but I think it's fine to use.

**Comment by hawkw** [comment]
Cool. I believe Codacy is currently set up to run all the code style checks from Effective Scala, plus a couple of additional checks I've enabled that I think are important. Do note that Codacy only runs code review on Scala code – any Java code in the repo is silently ignored.

If you're signing off on our coding standards being Effective Scala-based, I'll add a note in the readme stating that. If we want to build on Effective Scala and say "we also require x, y, and z", we can do that, as well.

**Comment by hawkw** [comment]
I've added a [page](https://github.com/MeteorCode/Pathway/wiki/Contributing-to-Pathway) on contributing to Pathway to the project wiki. If this seems reasonable to you, I'll add it to a markdown document in the repo itself as well, and put a link in the README.

We may also wish to come up with a Contributor License Agreement (CLA) for Pathway to avoid any legal troubles, but that's probably deserving of its own issue.

**Comment by hawkw** [comment]
I think this is finished.
