### ISSUE TITLE
A couple of weird build oddities

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#34]
While watching CI builds on Travis, I noticed a couple of oddities in our build process that we might want to look into.

1. For some reason, we invoke `gradle assemble` and then `gradle build`. This is weird, because `gradle build` depends on `gradle assemble` and [invokes it on its own](https://travis-ci.org/MeteorCode/Pathway#L459). Not sure why the Travis config has Travis run `gradle assemble` independently of `gradle build`.

2. When tests fail, Travis fails the build with a "build errored" rather than a "build failed" message. Typically, "build failed" should be displayed if tests have failed, while "build errored" should be displayed if something went wrong in the build process that wasn't a test failure. Since these have different semantic meanings, I'd like it if this could be fixed. I'd like to be able to differentiate between builds that fail due to failed tests and builds that failed due to build/CI issues. I'm not sure why build results are reported in this way, so we should look into that.

**Comment by ArcticLight** [comment]
This seems reasonable, but I don't know enough about Travis to fix this. As Hawk may be aware, my Internet has been down since Thursday, so I can't really do much about it right now anyway.

**Comment by hawkw** [comment]
Never mind on the first point, it looks like `gradle assemble` doesn't do what I thought it did. I thought `assemble` ran the build and then packaged the jars, but looking at the Gradle docs, it turns out that all `assemble` actually does is fetch the dependencies for the project. I think we may have at one point had the `assemble` task overridden with a definition that built our jars – this may have been a LibGDX thing – but it appears that this is no longer the case.

It looks like the reason Travis runs `assemble` before the build step is so that if fetching the dependencies fails, it can mark the build as "errored" rather than as "failed". I don't think Travis actually knows how to parse Gradle's results and figure out if the build errored or if it failed; I think that the only way it differentiates between those is that "build failed" means the actual build step failed, and "build errored" means something run before or after the build step failed.

**Comment by hawkw** [comment]
Closed as "invalid" as we are now using sbt (c0ed646eb200a5fbddd1a49867c6eaa44134e921).
