### ISSUE TITLE
Build is now completely broken on Travis for test-refactor

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#35]
See builds [#110](https://travis-ci.org/MeteorCode/Pathway/builds/64829223) and [#111](https://travis-ci.org/MeteorCode/Pathway/builds/64829525). My one bad guess at what might fix it (65f688d9ff55988cc14f01a6caf7be0f9cbfa792) obviously didn't work. 

I'm not seeing anything in the Git history that could have broken Travis's ability to find the Gradle executable, which is what appears to be going on. Any input from @ArcticLight would be greatly appreciated.

Sorry for breaking the build.

**Comment by hawkw** [comment]
Should add also that the latest master ([#108](https://travis-ci.org/MeteorCode/Pathway/builds/64816289)) seems to have built correctly. I cannot guarantee that this will be the case if somebody pushes additional code to master, though. Yikes.

**Comment by ArcticLight** [comment]
I have to get onto a PC to take a look at this. It will be a little while before I can.

**Comment by hawkw** [comment]
> I have to get onto a PC to take a look at this. It will be a little while before I can.

Take your time. Master still passes. :)

**Comment by hawkw** [comment]
Okay, deleting the Gradle wrapper script (16d6258) does fix it, but now it's saying that there was a failing test, which is funny 'cause, you know, [there weren't any](https://travis-ci.org/MeteorCode/Pathway/builds/64934724#L262). It's possible that the ignore tag in ScalaTest causes Gradle to see the ignored test as a failure, but that seems Wrong and Bad. I'll have to look into that.

Anyway, this problem is (temporarily) fixed. I'll see if regenerating a new Gradle wrapper script will make it work, I would like to be able to provide the wrapper on the repo for other devs, even if Travis doesn't need it.

**Comment by hawkw** [comment]
> It's possible that the ignore tag in ScalaTest causes Gradle to see the ignored test as a failure, but that seems Wrong and Bad. I'll have to look into that.

This doesn't appear to be the problem. I just ran the tests on my dev machine, and Gradle tells me that all the tests passed and that there were no exceptions. Ugh. Dammit.

**Comment by hawkw** [comment]
I reran the build on Travis and it still failed, so at least the issue is somewhat deterministic.

**Comment by hawkw** [comment]
I did some additional sleuthing and it looks like the initial cause of this issue may have been that the `gradlew` script was commited to the repo but the `gradle-wrapper.jar` jar file was not (and it is supposed to be). I regenerated the whole Gradle wrapper (6ec07cc012c23f974f0b4d67296345a68ac5a20c) so that should hopefully permit Travis to use the wrapper again. Making Travis use the wrapper will ensure consistent builds between dev and CI, which hopefully may fix the test failing issue as well.

**Comment by hawkw** [comment]
Okay, I've finally gotten Travis to use the Gradle wrapper, but build [#115](https://travis-ci.org/MeteorCode/Pathway/builds/64942439) is still failing with the same issue.

My one remaining theory is that it's possible that the [one test case](https://travis-ci.org/MeteorCode/Pathway/builds/64942439#L988) that's listed in white rather than green text is maybe somehow being reported incorrectly to Gradle by ScalaTest, so I'm going to try disabling that test and seeing if the build passes. I'd really like to know why this is taking place, though - this is really weirding me out, and it's really important that we're able tot rust in our tests being run as consistently as possible between dev and CI environments.

**Comment by hawkw** [comment]
HOLY CRAP my one last flailing [attempt](https://github.com/MeteorCode/Pathway/commit/1f71061f46bb2716a8875bcd481790023718abd9#commitcomment-11458183) at fixing the build [somehow actually worked](https://travis-ci.org/MeteorCode/Pathway/builds/64944108)??? What just happened. I don't understand!

**Comment by ArcticLight** [comment]
As a historical note on this closed issue, in the end it was discovered that the build was failing due to [pineapple craziness](https://xkcd.com/1457/) where the tests were sometimes being run and sometimes not being run.

**Clarifying note added in case we need to refer to this issue eventually in the future and are very confused about Hawk's prayer to the Travis gods.

**Comment by hawkw** [comment]
Yeah. Thanks for putting that there.
