### ISSUE TITLE
Publish ScalaDoc separately from JavaDoc

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#46]
Since we've split the Scala and Java APIs, we should publish ScalaDoc as well as JavaDoc to GitHub Pages. This is especially important as we've dropped GenJavaDoc (see #13), meaning that we are currently not publishing any up-to-date documentation on any of our Scala code, which currently comprises a majority of the Pathway codebase.

**Comment by ArcticLight** [comment]
I agree. Do we do this with Travis?

**Comment by hawkw** [comment]
We currently publish JavaDoc from Travis as part of the auto-release
process on tags, yeah. It's not too hard to just edit the scripts to
publish ScalaDoc as well.

**Comment by ArcticLight** [comment]
I'm okay with this thing. Max Votes Yes :thumbsup:

**Comment by hawkw** [comment]
Cool. I'll set it up.
