### ISSUE TITLE
Project gradle config requires Git

### ISSUE THREAD

**Issue by ArcticLight** [MeteorCode/Pathway#47]
I'm not sure what's up with our current Gradle configuration, but somehow the initial script compile makes dependencies on Git eventually. I know this, because while trying to set up development on Windows, I can't even run `.\gradlew tasks` because Gradle blows up when looking for `git` on my path.

I feel like we should either document this requirement (i.e. you need Git on your path to compile this) or we should fix the config such that the *buildscript* doesn't rely on Git

**Comment by hawkw** [comment]
IIRC this may be related to versioning builds with git hashes?

**Comment by ArcticLight** [comment]
We should at least document this somewhere, I think

**Comment by hawkw** [comment]
Fair enough. In the contrib page on the wiki?

**Comment by ArcticLight** [comment]
Sounds reasonable

**Comment by hawkw** [comment]
[This](https://github.com/MeteorCode/Pathway/wiki/Contributing-to-Pathway#what-youll-need) should do the trick.
