### ISSUE TITLE
Frozen spec incorrect

### ISSUE THREAD

**Issue by ArcticLight** [MeteorCode/Pathway#48]
I was just (finally) getting around to working on `freeze` and so (again, finally) looked at Hawk's test spec for a frozen ForkTable. Except that the test description is wrong, and so is the test.

Hawk appears to test that a parent (root) table is not modified when a sub-table key is added/modified. Except, this exact behavior should be invariant to ForkTable anyway, and I believe is a duplicate/corollary to the test spec for ` when -> forked -> should "not allow access keys defined in its forks"`

In fact, the behavior should be of the *opposite* relationship, i.e. when a sub-table is frozen, changes to its parents (and the root) should not affect the child's state.

**Comment by hawkw** [comment]
Oh crap. Oops. Yeah, that's kind of...obviously wrong! I'll fix that right away.

**Comment by hawkw** [comment]
> when a sub-table is frozen, changes to its parents (and the root) should not affect the child's state.

It looks like that's what's happening in the test? 

Here we fork a table, freeze the fork, bind a new key in the root level, and then assert that the changes to the root table don't effect the state of the frozen fork:

```scala
level2.freeze

// ...

root.put(4,4)

level2.get(4) shouldBe None
level2 should not contain (4 -> 4)
```

**Comment by ArcticLight** [comment]
https://github.com/MeteorCode/Pathway/blob/master/src/test/java/com/meteorcode/pathway/test/ForkTableSpec.scala#L296

**Comment by hawkw** [comment]
Yeah, you're right, that line is testing for behaviour that should be invariant across frozen/non-frozen `ForkTable`s – I'll remove it. 

But I'm still not sure how the test is _wrong_? It looks to me just like it's testing for some stuff that shouldn't be necessary to test for here, but that should still hold true?

**Comment by ArcticLight** [comment]
It holds true, but doesn't describe the label it's titled with. Seeing as the labels are supposed to function as self documentation, that means that the test isn't doing what it says it does. I'd consider that 'wrong'. Consider I wrote a test for the behavior "Property stamps should be gone once removed" and tested that a new event doesn't have any property stamps. That's a good test, but for the wrong behavior, and could cause plenty of debugging/quality problems just as if the test were bad

**Comment by hawkw** [comment]
Fair enough. I removed that code from the test and ran it, but your `freeze` code doesn't appear to pass this test. I'll push it up so you can try to fix it?

**Comment by ArcticLight** [comment]
Plox
