### ISSUE TITLE
ForkTable map() incorrect

### ISSUE THREAD

**Issue by ArcticLight** [MeteorCode/Pathway#49]
Something about ForkTable is currently on fire, namely:
```
var x = new ForkTable[Int, Int]()
var y = x.fork()
y.put(23,123)
x.put(3,1)
x.put(23,333)

y.collect({
  case (key,value) => s"[$key, $value]"
})
```

results not in the expected List([23,123], [3,1])
but instead in List([23,123], [23,333], [3,1]), which is wrong as it has a masked key installed in it

**Comment by hawkw** [comment]
Try out 9303f3fda3bf4b2c7da85ba3ce912c81a93d6e6f?

**Comment by hawkw** [comment]
Max's solution in 636ce1d should fix this. I'll just go ahead and merge #50
