### ISSUE TITLE
Select scripting language for game engine development

### ISSUE THREAD

**Issue by ArcticLight** [MeteorCode/Pathway#52]
We've talked briefly about possibly shelving BeanShell as language of choice, mainly because BeanShell doesn't have great security (it can instantiate anything on the system class loader) and is super old.

In the interests of getting ModLoader feature-complete (again) after removing BeanShell, we should select a new implementation language.

I would suggest Lua or Javascript mainly because they are the most common (and easiest to access because they have implementations that will run on the JVM) but am open to other suggestions.

Ultimately I feel like this one should be Hawk's final choice. I'll happily implement whatever language, but a choice does need to be made.

**Comment by hawkw** [comment]
I think we should use Common Lisp. Or Erlang. ;)

I am not all that familiar with Lua _or_ JS, but I feel like Lua is probably the better language, at least syntactically. Although choosing JS would permit Pathway devs to use any of the large set of languages that compile to JS, which fits in with my (probably impractical) desire to permit multiple scripting languages.

**Comment by hawkw** [comment]
I believe it has been decided that we will definitely be going with Java 8's Nashorn JavaScript implementation for security reasons?

**Comment by ArcticLight** [comment]
Not especially for security reasons, but the fact that it makes security easy-ish will be nice. If Hawk agrees, then we can go with this.

**Comment by hawkw** [comment]
Nashorn seems like a good choice to me; it's backed by Oracle, so it should be well-maintained and supported, and JS is a common language that a lot of people know.

**Comment by hawkw** [comment]
Here are some assorted additional thoughts I've had that we might want to consider:

 + What version of ExcemaScript does the Nashorn interpreter support? If it's ES6 compliant, we might want to design our script-facing API with the new features in ES6 in mind.
 + What methods are there for optimising the performance of JS running in Nashorn? Can commonly used scripts or hot code paths be precompiled to Java bytecode? Will this be done automagically or do we have to ask Nashorn to do it for us? Does JS running in Nashorn benefit from JVM JIT compilation?
 + Are there ways that we can provide Nashorn with more convenient access to specific Java classes and objects? It would be cool to provide less gross syntax for accessing Pathway model components.
 + The [Web Resource Optimizer for Java](https://code.google.com/p/wro4j/) (wro4j) is a Java library for managing web assets pipelines. I believe it contains a Java implementation of the CoffeeScript compiler. If we wanted to, I think we could use this to compile CoffeeScript scripts to JS before passing them to Nashorn to interpret. I don't know much about CoffeeScript, but I think @ArcticLight likes it...?

**Comment by ArcticLight** [comment]
> I think we could use this to compile Coffeescript [...]

I don't really think it's our job to compile Coffeescript for our mod authors, since they can do this themselves (and for any other compiled-to-JS language), but if Hawk likes this strongly I suppose we could do that.

> What version of ExcemaScript does the Nashorn [...]

I don't know, we'd have to find out.

> What methods are there [...]

I think (may be mistaken) that performance is Pretty Good(TM) according to Oracle, and there were advancements in using the J8 new dispatch things in bytecode that helped. I don't think we have to ask the platform to optimize for us, but I'm also not 100% certain

> we can provide Nashorn with more convenient access to specific [...]

If nothing else, we can still use the prelude / script context style insert-the-boilerplate scripts to provide this functionality for us. Since we handle the entire boot process, we can mangle the script environment however we like before it is passed to any mods.

**Comment by hawkw** [comment]
> I don't really think it's our job to compile Coffeescript for our mod author

Fair, I was sort of thinking that, too. Just figured it was worth putting out there.

> [...] performance is Pretty Good(TM) [...]

I'm sure it is; I just feel like Pathway is kind of spanning a lot of layers of indirection and I feel like we want to optimise those edges as aggressively as is reasonable.

> [...] we can still use the prelude / script context style insert-the-boilerplate scripts [...]

Yeah, I figured we'd do that, but we ought to see if there's an easier way to do it from the Java end. Storing types as `var`s seems to help though.

**Comment by hawkw** [comment]
I think this issue is closable? It seems like we've definitely agreed on Nashorn JS and are just discussing the specifics of how we're going to do that. I opened #57 to continue this dialogue.

**Comment by hawkw** [comment]
We might want to re-open this if we're still considering writing our own DSL using Truffle/Graal. @ArcticLight, is that something that's actually on the table?

**Comment by ArcticLight** [comment]
Not at the moment, I don't think.

**Comment by hawkw** [comment]
That's what I thought.
