### ISSUE TITLE
Test suite for new model

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#63]
Depends on #62. 

Once the new model architecture is stubbed out, I can go ahead and write the (failing) test suite describing the new model.

**Comment by ArcticLight** [comment]
We should have a conversation about what API we actually want in Model. Since we've thrown out (did that happen?) a bunch of the existing model as potentially being super braindead, we really need to discuss how we want to make model happen.

**Comment by hawkw** [comment]
> Since we've thrown out (did that happen?)

We haven't actually deleted anything yet, but we've decided most of it should be nuked. I've been trying to refactor stuff, but I feel like trying to refactor it is more of a pain in the ass than just totally throwing out most of it and rewriting it from scratch.

**Comment by hawkw** [comment]
Closed in 87529d0e47cb4963777037849b4dec1aa1de9861
