### ISSUE TITLE
Add JNI unpacking to IO

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#65]
As said by @ArcticLight on chat: 

> Pathway's IO module is now going to inherit some packing functionality to make this actually Happen. Hence, merging in the Tempo repo. This is because, re: our previous discussion about how to do JNI graphics within Java, we have taken the opinion that we will be Sad Minecraft, and that Pathway will unpack its natives and fork itself much like Other Launchers do.

I believe we should be able to incorporate the unpacking code from ArcticLight/Tempo, with some minimal clean-up and improvement.

**Comment by hawkw** [comment]
@ArcticLight:

>Tempo's code will need a bit of cleanup. I'd like to unpack into the OS-specific User directory, instead of dumping it out next to wherever the user has put the jar. so basically $USER_HOME on *nix or C:\Users\%self% on Windows

**Comment by hawkw** [comment]
Merging #67 should finish this.

**Comment by ArcticLight** [comment]
It appears that #67 is waiting on outstanding logger support, which we decided should probably be slf4j

**Comment by hawkw** [comment]
Um, no? I added logging with Typesafe's `scala-logging` package (which wraps SLF4J) in fa405e1429509d53a62de95cd0151e3ae4e0aa02, and I added logging to `Unpacker` in 80255ad9ec1b4c4a398e09ba50ce2b3609b5ccc2.

**Comment by hawkw** [comment]
That's in PR #69, which (if you think it looks good) we can merge back into `TempoMerge`, or straight into `master`.

**Comment by hawkw** [comment]
...and 5a5a17aad5dfd4e57ca0045788dfe07e83871a17 adds additional logging to `Unpacker`.
