### ISSUE TITLE
Fix equality/hash code rules for FileHandle

### ISSUE THREAD

**Issue by hawkw** [MeteorCode/Pathway#71]
Codacy is mad (with good reason) that we don't override `equals()` and `hashCode()` together for `FileHandle`. Currently, we allow two `FileHandle`s to equal each other if they point to the same path and are of the same type. However, since we don't also override `hashCode()`, two `FileHandle`s that are equal will not have the same hash codes, which is Bad and Wrong.

As I see it, we have the following options:
 +  Don't override `equals()` for `FileHandle`
 + Override `hashCode()` to be the hash code of the `FileHandle`'s path. That way, two `FileHandle`s with the same path will have the same hash code, and we can override equality to use the hash code. However, this also means a `ZipFileHandle` and a `FilesystemFileHandle` can equal each other, which seems like an issue.
 + Find some way to encode the type of the file handle in the hash code as well, maybe by having a constant for each subtype of `FileHandle` that's added to the path's hash. That way, two `ZipFileHandle`s into the same path can have the same hash, but a `FilesystemFileHandle` to the same path won't have the same hash code. This might be a small bit of work.

What does @ArcticLight  think?

**Comment by hawkw** [comment]
Here's what Codacy has to say:
### [Codacy](https://www.codacy.com/app/MeteorCode-Labs/Pathway/commit?cid=14006662) detected an issue:
#### Message: `You should implement equals and hashCode together`


#### Occurred on:
+ **Commit**: 23b9e702628347d3a76c8084df2281608026abfe
+ **File**: [src/main/java/com/meteorcode/pathway/io/scala/FileHandle.scala](https://github.com/MeteorCode/Pathway/blob/23b9e702628347d3a76c8084df2281608026abfe/src/main/java/com/meteorcode/pathway/io/scala/FileHandle.scala)
+ **LineNum**: [23](https://github.com/MeteorCode/Pathway/blob/23b9e702628347d3a76c8084df2281608026abfe/src/main/java/com/meteorcode/pathway/io/scala/FileHandle.scala#L23)
+ **Code**: `abstract class FileHandle(protected val virtualPath: String,`


#### Currently on:
+ **Commit**: d4d7cf4fc37fc98171b6e248238047d7f049c1ca
+ **File**: [src/main/scala/com/meteorcode/pathway/io/FileHandle.scala](https://github.com/MeteorCode/Pathway/blob/d4d7cf4fc37fc98171b6e248238047d7f049c1ca/src/main/scala/com/meteorcode/pathway/io/FileHandle.scala)
+ **LineNum**: [26](https://github.com/MeteorCode/Pathway/blob/d4d7cf4fc37fc98171b6e248238047d7f049c1ca/src/main/scala/com/meteorcode/pathway/io/FileHandle.scala#L26)

**Comment by ArcticLight** [comment]
What if it were the hashcode of, say `s"${this.class.getName()}@${this.virtualPath}"`

**Comment by hawkw** [comment]
Oh, wow, that's an obvious solution I was much too dumb to think of.
